server:
  port: 8090
spring:
  #mysql数据源
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=UTC
            username: root
            password: 123456
            driver-class-name: com.mysql.cj.jdbc.Driver
        sub:
          url: jdbc:mysql://localhost:3306/sys?characterEncoding=utf-8&serverTimezone=UTC
            username: root
            password: 123456
            driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    basic:
      path: /swagger-ui.html
      enabled: true
    user:
      name: test #账号
      password: 123456  #密码
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
